name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Test building of app
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Build library
      run: dotnet build
